#!/usr/bin/env bash

binary_name='pvector'

source_files=(
    main.cpp
    ../ex_1_1/fraction.cpp
)

header_files=(
    -I ../ex_1_1
)

g++ \
    "${source_files[@]}" \
    "${header_files[@]}" \
    -o "$binary_name"
